-- INSERT statements for Categories (18 rows)
INSERT INTO Categories (CategoryID, CategoryName, Description) VALUES
(1, 'Laptops & Computers', 'Laptops & Computers products within the Electronics product line.'),
(2, 'Audio & Headphones', 'Audio & Headphones products within the Electronics product line.'),
(3, 'Office Furniture', 'Office Furniture products within the Furniture product line.'),
(4, 'Home Furniture', 'Home Furniture products within the Furniture product line.'),
(5, 'Stationery', 'Stationery products within the Office Supplies product line.'),
(6, 'Printers & Ink', 'Printers & Ink products within the Office Supplies product line.'),
(7, 'Kitchen Appliances', 'Kitchen Appliances products within the Home & Kitchen product line.'),
(8, 'Home Decor', 'Home Decor products within the Home & Kitchen product line.'),
(9, 'Fitness Equipment', 'Fitness Equipment products within the Sports product line.'),
(10, 'Outdoor & Camping', 'Outdoor & Camping products within the Sports product line.'),
(11, 'Consoles', 'Consoles products within the Gaming product line.'),
(12, 'Gaming Accessories  ', 'Gaming Accessories products within the Gaming product line.'),
(13, 'Men''s Clothing', 'Men''s Clothing products within the Fashion product line.'),
(14, '  Women''s Clothing', 'Women''s Clothing products within the Fashion product line.'),
(15, 'Bags & Wallets', 'Bags & Wallets products within the Accessories product line.'),
(16, 'Watches & Jewelry', 'Watches & Jewelry products within the Accessories product line.'),
(17, 'Large Appliances', 'Large Appliances products within the Appliances product line.'),
(18, 'Small Appliances', 'Small Appliances products within the Appliances product line.');